### ISSUE TITLE
Configuration page required

### ISSUE THREAD

**Issue by nicolas59** [ligoj/ligoj#3]
Today, to configure plugins, we need to connect to the database and add configuration entries for using plugins.

I propose to add a configuration page like Jenkins to configure plugin.

**Comment by ligoj** [comment]
Indeed there is no UI for node. The service (for sample "build") and the tool (for sample "jenkins") are configured in the database at the first start after the download.
For the final node, instance of the tool, we need an UI using the parameters mechanisnm to fix some or all not provided parameters inherited from the tool/service.

**Comment by fdaugan** [comment]
Indeed there is no UI for node. The service (for sample "build") and the tool (for sample "jenkins") are configured in the database at the first start after the download.
For the final node, instance of the tool, we need an UI using the parameters mechanisnm to fix some or all not provided parameters inherited from the tool/service.

**Comment by fdaugan** [comment]
Fixed by cb72c50c2db033634665298e715c5b3052a96207
