### ISSUE TITLE
Ajout Personne à un groupe KO

### ISSUE THREAD

**Issue by sguisse** [ligoj/ligoj#5]
La fonctionnalité d'ajout de personne à un groupe est accessible 
- Je peu sélectionner un user
- Appuyer sur le bouton "Ajouter cet utilisateur au groupe"

Mais rien ne se semble se passer
- Pas de rafraichissement du tableau
- Pas d'affichage d'erreur
- Pas de prise en compte de l'action après rafraichissement de l'écran

Cf PJ
![image](https://cloud.githubusercontent.com/assets/7907677/25939349/dba2529c-3632-11e7-9e6d-845cb04602b9.png)

**Comment by fdaugan** [comment]
Plusieurs sources possibles mais plus probablement une délégation en écriture manquante pour ce groupe.
Il y a une demande (JIRA Gfi) qui adresse ce problème. Le bouton d'ajout ne devrait tout simplement pas être accessible pour les utilisateurs ne disposant pas de droits suffisant pour ce groupe. Le contrôle métier rejette l'opération. Il manque donc le check des droits au niveau UI pour masquer ou désactiver ces composants en reflétant les autorisations métiers (RBAC) comme cela est fait sur les autres écrans.
Donc si tu es légitiment le gestionnaire de ce compte, la délégation qui t'a été attribué pour ce groupe n'est pas complète car il manque le droit d'écriture. Et si tu veux pouvoir propager ce groupe à d'autres personnes, il te faudra le droit "admin", équivalant par analogie au privilège GRANT dans SQL.

**Comment by ligoj** [comment]
Est-ce encore d'actualité?
