### ISSUE TITLE
Unable to lock an user

### ISSUE THREAD

**Issue by sguisse** [ligoj/ligoj#56]
**lpetain** user left the company, I want to lock it.

Locking this user thorws an error : 
==> Pas de user avec identifiant **lpetain**

This user exists, I can see it, see screenshot
![image 2](https://user-images.githubusercontent.com/7907677/35291592-17f2e94a-006e-11e8-9b79-36d4ff385f09.png)

**Comment by fdaugan** [comment]
There are several points:
- You have the READ permission on the company of this user, so you can see it. But you have not the WRITE permission. Without this WRITE right, you cannot update any attribute of any user from this company
- The message is irrelevant. It should not be "user X does not exist". This message is the default one, and is used to avoid to reveal the existing users from illegal access.
- The UI should not display this "lock" option if you cannot use it
