### ISSUE TITLE
display secured parameters in a password input

### ISSUE THREAD

**Issue by alocquet** [ligoj/ligoj#6]
In project subscription wizzard, parameter values can be filled in text input.
Secured parameters should be filled in password type inputs ?

**Comment by ligoj** [comment]
There is 2 security levels : 
- data at rest with "secured", AES crypto in the database. This data is never exposed outside the server, cannot be used in SQL filtering, used at UI level to build URL, etc.
- data presentation level only based on the name. Basically, any parameter identifier containing "password" is rendered as "<input type="password">"

So a sensitive parameter should "secured". But a sensitive data does not imply input password. Either name the parameter containg "password", either register your parameter to be rendered as a password.
Bellow  sample plugin code registering a a parameter to be rendered as a password :
```javascript
configureSubscriptionParameters: function (configuration) {
  configuration.providers['service:what:ever:param1'] = function(parameter) {
    return $('<input class="form-control parameter" type="password" autocomplete="off" data-type="' + parameter.type + '" id="' + parameter.id + '"' + (parameter.mandatory ? ' required' : '') + '>');
  };
}
```

**Comment by ligoj** [comment]
I've just added in the detection pattern "secret" in addition of "password"

**Comment by fdaugan** [comment]
I've just added in the detection pattern "secret" in addition of "password"
